name: Build

on:
  workflow_dispatch:

jobs:
  build_android:
    name: 🤖 Build Android App
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "temurin"
      - run: flutter pub get
      - name: Extract Version from pubspec.yaml
        id: extract_version
        run: |
          echo "VERSION=$(grep '^version: ' pubspec.yaml | sed 's/version: //')" >> $GITHUB_ENV
      - run: flutter build apk --release
      - name: Upload APK to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/app/outputs/flutter-apk/app-release.apk
          tag: ${{ env.VERSION }}
          overwrite: true
          body: "Stable"
